{"name": "test_001", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n  +2\n  -1", "trace": "self = <com.yang.practice100.POM.TestSuites.test_demo.TestClass object at 0x0000028A890F7640>\n\n    def test_001(self):\n        print('Test_01下的用例001登陆')\n    \n>       assert  2 == 1\nE       assert 2 == 1\nE         +2\nE         -1\n\nTestSuites\\test_demo.py:44: AssertionError"}, "attachments": [{"name": "log", "source": "6d5b5276-3d1d-4a6c-b76c-337827aa0738-attachment.txt", "type": "text/plain"}], "start": 1666666224890, "stop": 1666666224891, "uuid": "32e8f885-afa0-4621-8aa3-845e114f81bb", "historyId": "683ce27957ddc67fb26a20cef6dfb4b5", "testCaseId": "92a2db69f2d17c1a5a53d6b3048d49c4", "fullName": "TestSuites.test_demo.TestClass#test_001", "labels": [{"name": "parentSuite", "value": "TestSuites"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-FOQS77R"}, {"name": "thread", "value": "20812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSuites.test_demo"}]}